### ISSUE TITLE
tt_user_videos - more than 30 URLs?

### ISSUE THREAD

**Issue by andersolarsson** [JBGruber/traktok#1]
Hello,

First of all, thank you for this port! I was wondering if it is somehow possible to get more than 30 URLs using `tt_user_videos`. I am trying to get the full set of URLs for accounts that have posted more than 30 videos.

Best,
Anders

**Comment by JBGruber** [comment]
I tried to implement it, but for every new "page", TikTok wants a header named `x-tt-params`, which I do not know how to generate. There is some discussion in this issue, but it's beyond my knowledge of encryption: https://github.com/davidteather/TikTok-Api/issues/899#issuecomment-1175439842. If you have any hints how to do this in R, let me know.

**Comment by JBGruber** [comment]
Out of scope for now.
