### ISSUE TITLE
tt_user_info_api error handling problem

### ISSUE THREAD

**Issue by vot4ntonio** [JBGruber/traktok#15]
I get error in `purrr::map()`  when querying for multiple users and one of them does not exists anymore.
Is there a way to handle this error and just skip the non-existing users? 
Otherwise, I have to perform multiple requests until my list of usernames is cleaned from nonexisiting users.

> Error in `purrr::map()`:
> ℹ In index: 16.
> Caused by error in `httr2::req_perform()`:
> ! HTTP 400 Bad Request.
> • status: invalid_params
> • message: `username: XXXXXXX` is invalid: cannot find the user
> • log_id: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by JBGruber** [comment]
That sounds reasonable and I'll get to it. Thanks for the suggestion. Could send me an example for testing? Or does this happen with any random non-existing handle?

**Comment by JBGruber** [comment]
Have a look if this works for you. I tested it with 50 of the usernames you sent me and it works well:

```
library(traktok)
users <- readLines("usernames.txt")[1:50]
df <- tt_user_info_api(username = users)
```

If a user does no longer exist, it gives you a warning, but does not throw an error. If you run into more problems, let me know and I can reopen the issue.
