### ISSUE TITLE
tt_user_info_api only returns TRUE

### ISSUE THREAD

**Issue by bachl** [JBGruber/traktok#16]
Hi Johannes,
First of all, thank you for your work on this super useful package!
I just got approved for research data access and ran some first tests. When testing

```r
tt_user_info_api("jbgruber")
``` 

I got the output in the console:
```
✔ Got user jbgruber [206ms]
``` 

But the function only returned `TRUE`.

Thank you for looking into that.

**Comment by JBGruber** [comment]
Yes, this was a dumb bug. Thanks for letting me know! Should work now:

``` r
traktok::tt_user_info_api("jbgruber")
#> ℹ Getting user jbgruber
#> ✔ Got user jbgruber [860ms]
#> 
#> # A tibble: 1 × 8
#>   likes_count video_count avatar_url bio_description display_name follower_count
#>         <int>       <int> <chr>      <chr>           <chr>                 <int>
#> 1           3           2 https://p… ""              jbgruber                  2
#> # ℹ 2 more variables: following_count <int>, is_verified <lgl>
```

<sup>Created on 2024-05-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
