### ISSUE TITLE
HTTP 500 Internal Server Error during API Calls

### ISSUE THREAD

**Issue by massimo-terenzi** [JBGruber/traktok#18]
Hi, I’m using the `tt_search_api` function to make API calls to TikTok’s research API. I’ve noticed a strange behavior: after a few successful attempts, I receive a `500 Internal Server Error` from the server. 

I’m not sure if this is related to traktok or if it’s an issue with TikTok’s API. Anyone else? 

Thank you,
Massimo

**Comment by JBGruber** [comment]
I've encountered this as well and made sure the functions retries 5 times before failing. It seems to be the API that is misbehaving here, and I can usually get the correct response when I use the same query again. Note that in these cases, you can use `last_query()` to get all videos already found. See also these instructions on picking up an old search: https://jbgruber.github.io/traktok/articles/research-api.html#dealing-with-rate-limits-and-continuing-old-searches
