### ISSUE TITLE
Video download broken

### ISSUE THREAD

**Issue by strohne** [JBGruber/traktok#22]
Hi, downloading videos using the hidden API seems to be broken since some days. I didn't dig deep yet and this is probably not a package issue, more related to the TikTok page.

```
cookiemonster::add_cookies("cookies.txt")
url <- "https://www.tiktok.com/HANDLEHERE/video/IDHERE"
videos_df <- tt_videos_hidden(url, dir="videos")
```

I'm glad about any hints.

Cheers, Jakob :)

**Comment by JBGruber** [comment]
Can you please try again? I noticed `is_slides` is not a value returned by TikTok, but one I determine based on a heuristic that might be wrong.

**Comment by strohne** [comment]
Thanks a lot, it's working. 🚀 

(We tried on three different machines, Win and Mac, with different URLs when it was not working. Then we tried on a Win machine after your fix - still not working. But I guess we forgot to restart the R session after updating the package. 🙈  By now, it works like a charm on my Win machine)

**Comment by strohne** [comment]
By the way...my first intuition was that TikTok cross-checks the user-agent with the cookies, maybe not for equality, but for similarity. Or checks the user-agent, regardless of cookies. Might be a completely false assumption. But maybe add user-agent headers in the package? From my experience, that's a basic trap when working with hidden APIs.
